apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: payment-memory-stress
  namespace: simulation
spec:
  mode: one
  selector:
    namespaces:
      - simulation
    labelSelectors:
      app: simulation-paymentservice
  stressors:
    memory:
      size: "256Mi"
  duration: "2m"