apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-simulation-payment
  namespace: simulation-normal
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - simulation-normal
    labelSelectors:
      app: simulation-payment
