apiVersion: v1
kind: Pod

metadata:
  name: k6-runner
  namespace: simulation-resource

spec:
  restartPolicy: Never

  containers:
    - name: k6

      image: grafana/k6:latest

      command:
        - k6
        - run
        - /scripts/payment-test.js

      volumeMounts:
        - name: workload
          mountPath: /scripts

  volumes:
    - name: workload
      configMap:
        name: k6-workload
