import os
import sys

sys.path.append(
    os.path.dirname(__file__)
)

from services.llm_service import (
    generate_environment_parameters
)

from services.environment_validator import (
    validate_environment_parameters
)

from services.chaos_template_service import (
    generate_chaos_yaml
)


# --------------------------------
# Application
# --------------------------------

application = {
    "kind": "Deployment",

    "name": "simulation-payment",

    "namespace": "simulation-resource",

    "replicas": 1,

    "containers": [
        {
            "name": "payment",

            "image": "nginx:latest",

            "ports": [
                {
                    "containerPort": 80
                }
            ],

            "resources": {
                "requests": {
                    "cpu": "100m",
                    "memory": "64Mi"
                },

                "limits": {
                    "cpu": "500m",
                    "memory": "128Mi"
                }
            }
        }
    ]
}


# --------------------------------
# Selected environments
# --------------------------------

environments = [
    "CPU Stress",
    "Memory Stress",
    "Network Delay",
    "Network Loss"
]


# --------------------------------
# User constraints
# --------------------------------

cpu = "2 cores"
memory = "4Gi"
vus = 10
duration = 60


# --------------------------------
# Step 1: LLM
# --------------------------------

print("\n===== GENERATING PARAMETERS =====")

result = generate_environment_parameters(
    application,
    environments,
    cpu,
    memory,
    vus,
    duration
)

print(result)


# --------------------------------
# Step 2: Validate
# --------------------------------

print("\n===== VALIDATING PARAMETERS =====")

valid, message = validate_environment_parameters(
    result,
    application
)

print("Valid:", valid)
print("Message:", message)


if not valid:
    raise RuntimeError(
        "Generated parameters failed validation."
    )


# --------------------------------
# Step 3: Render templates
# --------------------------------

print("\n===== GENERATING CHAOS YAML =====")

generated = result["environments"]

for environment in environments:

    parameters = generated[environment]

    # System-controlled parameters
    # are added here, NOT generated by LLM.

    if environment == "CPU Stress":

        parameters.update({
            "chaos_name": "compound-cpu-stress",
            "namespace": "simulation-resource",
            "mode": "one",
            "target_app": "simulation-payment",
            "workers": 1,
            "cpu_load": parameters.get("value"),
            "duration": f"{duration}s"
        })

    elif environment == "Memory Stress":

        parameters.update({
            "chaos_name": "compound-memory-stress",
            "namespace": "simulation-resource",
            "mode": "one",
            "target_app": "simulation-payment",
            "workers": 1,
            "memory_size": parameters.get("value"),
            "duration": f"{duration}s"
        })

    elif environment == "Network Delay":

        parameters.update({
            "chaos_name": "compound-network-delay",
            "namespace": "simulation-resource",
            "mode": "one",
            "target_app": "simulation-payment",
            "jitter": "10ms",
            "correlation": "0",
            "latency": parameters.get("value"),
            "duration": f"{duration}s"
        })

    elif environment == "Network Loss":

        parameters.update({
            "chaos_name": "compound-network-loss",
            "namespace": "simulation-resource",
            "mode": "one",
            "target_app": "simulation-payment",
            "correlation": "0",
            "loss_percent": parameters.get("value"),
            "duration": f"{duration}s"
        })


    yaml_content = generate_chaos_yaml(
        environment,
        parameters
    )

    print(
        f"\n===== {environment} =====\n"
    )

    print(yaml_content)

