import json
import os

# Load environment generated by Groq
with open("generated/environment.json") as f:
    env = json.load(f)

service = env["service"]

# Use the existing Online Boutique paymentservice image
image = "gcr.io/google-samples/microservices-demo/paymentservice:v0.10.3"
yaml = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-{service}
  namespace: simulation
spec:
  replicas: {env["replicas"]}
  selector:
    matchLabels:
      app: simulation-{service}
  template:
    metadata:
      labels:
        app: simulation-{service}
    spec:
      containers:
        - name: {service}
          image: {image}
          resources:
            requests:
              cpu: {env["cpu_request"]}
              memory: {env["memory_request"]}
            limits:
              cpu: {env["cpu_limit"]}
              memory: {env["memory_limit"]}
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-{service}
  namespace: simulation
spec:
  selector:
    app: simulation-{service}
  ports:
    - port: 50051
      targetPort: 50051
"""

os.makedirs("generated", exist_ok=True)

with open("generated/deployment.yaml", "w") as f:
    f.write(yaml)

print("Kubernetes configuration generated!")
print("File: generated/deployment.yaml")
