apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos

metadata:
  name: {{ chaos_name }}
  namespace: {{ namespace }}

spec:
  mode: {{ mode }}

  selector:
    namespaces:
      - {{ namespace }}

    labelSelectors:
      app: {{ target_app }}

  stressors:
    memory:
      workers: {{ workers }}
      size: "{{ memory_size }}"

  duration: "{{ duration }}"