apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos

metadata:
  name: {{ chaos_name }}
  namespace: {{ namespace }}

spec:
  action: pod-kill

  mode: {{ mode }}

  selector:
    namespaces:
      - {{ namespace }}

    labelSelectors:
      app: {{ target_app }}